version: "2"
run:
  concurrency: 8
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - dupl
    - durationcheck
    - errorlint
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    govet:
      enable:
        - shadow
    wsl_v5:
      enable:
        - assign
        - branch
        - decl
        - defer
        - expr
        - for
        - go
        - if
        - inc-dec
        - label
        - range
        - return
        - select
        - switch
        - type-switch
        - append
        - assign-expr
        - err
        - leading-whitespace
        - trailing-whitespace
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: G115
      - path: (.+)\.go$
        text: G204
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: should have comment or be unexported
      - path: (.+)\.go$
        text: comment on exported const
      - path: (.+)\.go$
        text: should have comment \(or a comment on this block\)
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: package-comments
    paths:
      - bin
      - vendor
      - var
      - tmp
      - .cache
      - third_party$
      - builtin$
      - examples$
