# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable:
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
  exclude-use-default: false
  exclude:
    - G104
    - G115
    - G204
    - should have a package comment
    - should have comment or be unexported
    - comment on exported const
    - should have comment \(or a comment on this block\)
    - don't use an underscore in package name
    - package-comments
