# More info on config here: https://golangci-lint.run/usage/configuration/
run:
  concurrency: 4
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
  allow-parallel-runners: true

output:
  sort-results: true

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 3
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/Format-C-eft/git-update
  gosec:
    excludes:
      - G204

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - goimports
    - gosec